//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MLOpenInterface.wsFeature {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CSDSoap", Namespace="http://ws.nuig.csd")]
    public partial class CSD : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetFeatureOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CSD() {
            this.Url = global::MLOpenInterface.Properties.Settings.Default.MLOpenInterface_wsFeature_CSD;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetFeatureCompletedEventHandler GetFeatureCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.nuig.csd/csd.WSService.GetFeature", RequestNamespace="http://ws.nuig.csd", ResponseNamespace="http://ws.nuig.csd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WSFeature GetFeature(string toAddress, string ccAddress, string subject, string mailbody) {
            object[] results = this.Invoke("GetFeature", new object[] {
                        toAddress,
                        ccAddress,
                        subject,
                        mailbody});
            return ((WSFeature)(results[0]));
        }
        
        /// <remarks/>
        public void GetFeatureAsync(string toAddress, string ccAddress, string subject, string mailbody) {
            this.GetFeatureAsync(toAddress, ccAddress, subject, mailbody, null);
        }
        
        /// <remarks/>
        public void GetFeatureAsync(string toAddress, string ccAddress, string subject, string mailbody, object userState) {
            if ((this.GetFeatureOperationCompleted == null)) {
                this.GetFeatureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFeatureOperationCompleted);
            }
            this.InvokeAsync("GetFeature", new object[] {
                        toAddress,
                        ccAddress,
                        subject,
                        mailbody}, this.GetFeatureOperationCompleted, userState);
        }
        
        private void OnGetFeatureOperationCompleted(object arg) {
            if ((this.GetFeatureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFeatureCompleted(this, new GetFeatureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.nuig.csd")]
    public partial class WSFeature {
        
        private string mailboxField;
        
        private string subjectField;
        
        private string bodyField;
        
        private string messageCleanTaggedField;
        
        private long followUpField;
        
        private bool followUpFieldSpecified;
        
        private long mailToCountField;
        
        private bool mailToCountFieldSpecified;
        
        private long mailCCCountField;
        
        private bool mailCCCountFieldSpecified;
        
        private long w5Field;
        
        private bool w5FieldSpecified;
        
        private long arrivalTimeField;
        
        private bool arrivalTimeFieldSpecified;
        
        private long lengthField;
        
        private bool lengthFieldSpecified;
        
        /// <remarks/>
        public string Mailbox {
            get {
                return this.mailboxField;
            }
            set {
                this.mailboxField = value;
            }
        }
        
        /// <remarks/>
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        public string Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        public string MessageCleanTagged {
            get {
                return this.messageCleanTaggedField;
            }
            set {
                this.messageCleanTaggedField = value;
            }
        }
        
        /// <remarks/>
        public long FollowUp {
            get {
                return this.followUpField;
            }
            set {
                this.followUpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FollowUpSpecified {
            get {
                return this.followUpFieldSpecified;
            }
            set {
                this.followUpFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long MailToCount {
            get {
                return this.mailToCountField;
            }
            set {
                this.mailToCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MailToCountSpecified {
            get {
                return this.mailToCountFieldSpecified;
            }
            set {
                this.mailToCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long MailCCCount {
            get {
                return this.mailCCCountField;
            }
            set {
                this.mailCCCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MailCCCountSpecified {
            get {
                return this.mailCCCountFieldSpecified;
            }
            set {
                this.mailCCCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long W5 {
            get {
                return this.w5Field;
            }
            set {
                this.w5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool W5Specified {
            get {
                return this.w5FieldSpecified;
            }
            set {
                this.w5FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long ArrivalTime {
            get {
                return this.arrivalTimeField;
            }
            set {
                this.arrivalTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ArrivalTimeSpecified {
            get {
                return this.arrivalTimeFieldSpecified;
            }
            set {
                this.arrivalTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LengthSpecified {
            get {
                return this.lengthFieldSpecified;
            }
            set {
                this.lengthFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetFeatureCompletedEventHandler(object sender, GetFeatureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFeatureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFeatureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSFeature Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSFeature)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591